import { SERVICE_THUMBS } from "./serviceImages";
import { brand } from "./brand";

// Native, labelled offer rails — NoBrokerHood style. Each tab has an
// "Offers for you" strip of brand cards (promo code + image). Optional
// "In the Spotlight" banners sit under the rail on Home Services.

export const AD_SLOTS = {
  home: {
    title: "Offers nearby",
    hint: "Optional partner deals in this neighbourhood",
  },
  community: {
    title: "Offers for you",
    hint: "Local services neighbours use",
  },
  bills: {
    title: "Offers for you",
    hint: "Home & money — after your bills",
  },
  amenities: {
    title: "Offers for you",
    hint: "Catering, décor & celebration",
  },
  visitors: {
    title: "Offers for you",
    hint: "Cabs, laundry, moving — after your log",
  },
  marketplace: {
    title: "Offers for you",
    hint: "Sits with listings, not over them",
  },
  home_services: {
    title: "Offers for you",
    hint: "First-booking deals from partners",
  },
};

export const CAMPAIGNS = {
  home: [
    {
      id: "freshbite",
      brand: "FreshBite",
      title: "Groceries in 15 min",
      subtitle: "₹150 off the first order for this society",
      cta: "Order",
      code: "SOCIETY150",
      color: "#1BA672",
      icon: "basket-outline",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=900&q=80",
      link: "https://www.example.com",
    },
    {
      id: "brew",
      brand: "Brew & Co.",
      title: "Buy 1 get 1 coffee",
      subtitle: "Clubhouse-side cafe · today only",
      cta: "Claim",
      code: "BOGOCAFE",
      color: "#6F4E37",
      icon: "cafe-outline",
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80",
      link: "https://maps.google.com/?q=cafe+near+me",
    },
    {
      id: "reebok",
      brand: "Reebok",
      title: "40% off training gear",
      subtitle: "Pickup from the society store this weekend",
      cta: "Shop",
      code: "REEBOK40",
      color: "#E4002B",
      icon: "fitness-outline",
      image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=900&q=80",
      link: "https://www.reebok.com",
    },
  ],
  community: [
    {
      id: "tuition",
      brand: "BrightMinds",
      title: "Board exam tuition",
      subtitle: "From a teacher in Tower B",
      cta: "Enquire",
      code: "TOWERB10",
      color: "#6D3BD1",
      icon: "school-outline",
      image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80",
      link: "https://www.example.com",
    },
    {
      id: "salon",
      brand: "Glow Studio",
      title: "Home salon in 45 min",
      subtitle: "Women & kids · this society",
      cta: "Book",
      code: "GLOW45",
      color: "#C2571A",
      icon: "cut-outline",
      image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
      serviceSlug: "salon",
    },
    {
      id: "kirana",
      brand: "Society Kirana",
      title: "Daily milk & bread",
      subtitle: "Leave at gate · billed monthly",
      cta: "Subscribe",
      code: "KIRANA1",
      color: "#0B6E8F",
      icon: "storefront-outline",
      image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=600&q=80",
      link: "https://www.example.com",
    },
  ],
  bills: [
    {
      id: "solar",
      brand: "SunGrid",
      title: "Cut your electricity bill",
      subtitle: "Rooftop solar with society AMC",
      cta: "Get quote",
      code: "SOLAR15",
      color: "#C99000",
      icon: "sunny-outline",
      image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
      link: "https://www.example.com",
    },
    {
      id: "paint",
      brand: "WallMint",
      title: "Interior in 3 days",
      subtitle: "10% off after you pay dues",
      cta: "See packs",
      code: "PAINT10",
      color: "#1E7A3D",
      icon: "color-palette-outline",
      image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&q=80",
      serviceSlug: "painting",
    },
    {
      id: "loan",
      brand: "HomeFirst",
      title: "Top-up against your flat",
      subtitle: "Pre-approved for this society",
      cta: "Check",
      code: "HOMEFIRST",
      color: "#0B6E8F",
      icon: "cash-outline",
      image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80",
      link: "https://www.example.com",
    },
  ],
  amenities: [
    {
      id: "cater",
      brand: "PlateUp",
      title: "Clubhouse catering",
      subtitle: "From ₹349 / plate · veg & Jain",
      cta: "Menu",
      code: "PLATE349",
      color: "#B42318",
      icon: "fast-food-outline",
      image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=600&q=80",
      link: "https://www.example.com",
    },
    {
      id: "decor",
      brand: "Festoon",
      title: "Birthday décor in 2 hrs",
      subtitle: "Balloon & theme setups",
      cta: "Book",
      code: "FESTOON15",
      color: "#7A5AF8",
      icon: "color-wand-outline",
      image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&q=80",
      link: "https://www.example.com",
    },
    {
      id: "cake",
      brand: "BakeHouse",
      title: "Same-day cakes",
      subtitle: "Delivered to the clubhouse",
      cta: "Order",
      code: "CAKE20",
      color: "#C2571A",
      icon: "ice-cream-outline",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
      link: "https://www.example.com",
    },
  ],
  visitors: [
    {
      id: "cab",
      brand: "CityCab",
      title: "Cab to the gate in 4 min",
      subtitle: "Pin drops at your tower",
      cta: "Ride",
      code: "GATE4",
      color: "#1B2B33",
      icon: "car-outline",
      image: SERVICE_THUMBS.cab,
      link: "https://www.example.com",
    },
    {
      id: "laundry",
      brand: "Washly",
      title: "Laundry pickup at gate",
      subtitle: "Leave-at-gate already supported",
      cta: "Schedule",
      code: "WASHLY24",
      color: "#0B6E8F",
      icon: "shirt-outline",
      image: SERVICE_THUMBS.laundry,
      serviceSlug: "laundry",
    },
    {
      id: "move",
      brand: "PorterGo",
      title: "Shifting this weekend?",
      subtitle: "Packers who know this society",
      cta: "Estimate",
      code: "MOVE10",
      color: "#C2571A",
      icon: "cube-outline",
      image: SERVICE_THUMBS.movers,
      serviceSlug: "movers",
    },
  ],
  marketplace: [
    {
      id: "urbanladder",
      brand: "Nest Home",
      title: "Sofa sets from ₹12,990",
      subtitle: "Free delivery into this society",
      cta: "Browse",
      code: "NEST12",
      color: "#6D3BD1",
      icon: "bed-outline",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      serviceSlug: "interiors",
    },
  ],
  home_services: [
    {
      id: "carpentry",
      brand: "Tower Trades Co.",
      title: "Carpentry offer",
      subtitle: "10% off on first booking",
      cta: "Book",
      code: "NEWAPP10",
      color: "#C2571A",
      icon: "hammer-outline",
      image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
      serviceSlug: "trades",
    },
    {
      id: "elec-offer",
      brand: `${brand.name} Instant`,
      title: "Electrician offer",
      subtitle: "10% off on first booking",
      cta: "Book",
      code: "NEWAPP10",
      color: "#0B6E8F",
      icon: "flash-outline",
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
      serviceSlug: "instant",
    },
    {
      id: "appliance",
      brand: "CoolAir Partners",
      title: "Appliance repair offer",
      subtitle: "10% off on first booking",
      cta: "Book",
      code: "NEWAPP50",
      color: "#0B6E8F",
      icon: "snow-outline",
      image: SERVICE_THUMBS.ac,
      serviceSlug: "ac",
    },
  ],
};

export const SPOTLIGHT = {
  home_services: [
    {
      id: "fan1",
      brand: "CoolAir Partners",
      title: "Fan cleaning at just ₹1",
      subtitle: "4.9 rated partners · 20L+ happy customers",
      badge: "STEAL DEAL",
      cta: "Claim offer now",
      color: "#128C4A",
      image: SERVICE_THUMBS.ac,
      serviceSlug: "ac",
    },
    {
      id: "clean1",
      brand: "Sparkle Homes",
      title: "2 BHK deep clean ₹999",
      subtitle: "Same-week slots inside this society",
      badge: "SOCIETY DEAL",
      cta: "Book cleaning",
      color: "#0B6E8F",
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=900&q=80",
      serviceSlug: "cleaning",
    },
  ],
  home: [
    {
      id: "payback",
      brand: `${brand.name} Rewards`,
      title: "Pay maintenance, get 2% back",
      subtitle: "Credited to next month's bill",
      badge: "REWARDS",
      cta: "Pay now",
      color: "#0B6E8F",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80",
      route: "Maintenance",
    },
  ],
};

export function adsFor(slot) {
  return CAMPAIGNS[slot] || CAMPAIGNS.home;
}

export function spotlightFor(slot) {
  return SPOTLIGHT[slot] || [];
}

export function slotMeta(slot) {
  return AD_SLOTS[slot] || AD_SLOTS.home;
}
